
// Constantes de permisos del sistema
export const PERMISOS = {
  // Usuarios
  USUARIOS_VER: 'USUARIOS_VER',
  USUARIOS_CREAR: 'USUARIOS_CREAR',
  USUARIOS_EDITAR: 'USUARIOS_EDITAR',
  USUARIOS_ELIMINAR: 'USUARIOS_ELIMINAR',

  // Permisos
  PERMISOS_GESTIONAR: 'PERMISOS_GESTIONAR',

  // Roles
  ROLES_VER: 'ROLES_VER',
  ROLES_CREAR: 'ROLES_CREAR',
  ROLES_EDITAR: 'ROLES_EDITAR',
  ROLES_ELIMINAR: 'ROLES_ELIMINAR',

  // Archivos
  ARCHIVOS_VER: 'ARCHIVOS_VER',
  ARCHIVOS_CREAR: 'ARCHIVOS_CREAR',
  ARCHIVOS_EDITAR: 'ARCHIVOS_EDITAR',
  ARCHIVOS_ELIMINAR: 'ARCHIVOS_ELIMINAR',

  // Mensajes
  MENSAJES_VER: 'MENSAJES_VER',
  MENSAJES_CREAR: 'MENSAJES_CREAR',
  MENSAJES_EDITAR: 'MENSAJES_EDITAR',
  MENSAJES_ELIMINAR: 'MENSAJES_ELIMINAR',

  // Notificaciones
  NOTIFICACIONES_VER: 'NOTIFICACIONES_VER',
  NOTIFICACIONES_CREAR: 'NOTIFICACIONES_CREAR',
  NOTIFICACIONES_EDITAR: 'NOTIFICACIONES_EDITAR',
  NOTIFICACIONES_ELIMINAR: 'NOTIFICACIONES_ELIMINAR',

  // Auditoría
  AUDITORIA_VER: 'AUDITORIA_VER',
  AUDITORIA_CREAR: 'AUDITORIA_CREAR',
  AUDITORIA_EDITAR: 'AUDITORIA_EDITAR',
  AUDITORIA_ELIMINAR: 'AUDITORIA_ELIMINAR',
  AUDITORIA_PRESUPUESTO_HISTORIAL: 'AUDITORIA_PRESUPUESTO_HISTORIAL',

  // SMTP Client
  SMTP_CLIENT_VER: 'SMTP_CLIENT_VER',
  SMTP_CLIENT_CREAR: 'SMTP_CLIENT_CREAR',
  SMTP_CLIENT_EDITAR: 'SMTP_CLIENT_EDITAR',
  SMTP_CLIENT_ELIMINAR: 'SMTP_CLIENT_ELIMINAR',

  // Plantillas de Notificación
  PLANTILLA_NOTIFICACION_VER: 'PLANTILLA_NOTIFICACION_VER',
  PLANTILLA_NOTIFICACION_CREAR: 'PLANTILLA_NOTIFICACION_CREAR',
  PLANTILLA_NOTIFICACION_EDITAR: 'PLANTILLA_NOTIFICACION_EDITAR',
  PLANTILLA_NOTIFICACION_ELIMINAR: 'PLANTILLA_NOTIFICACION_ELIMINAR',

  // Envíos de Notificación
  ENVIO_NOTIFICACION_VER: 'ENVIO_NOTIFICACION_VER',
  ENVIO_NOTIFICACION_CREAR: 'ENVIO_NOTIFICACION_CREAR',
  ENVIO_NOTIFICACION_EDITAR: 'ENVIO_NOTIFICACION_EDITAR',
  ENVIO_NOTIFICACION_ELIMINAR: 'ENVIO_NOTIFICACION_ELIMINAR',

  // Ejemplo Categoría
  EJEMPLO_CATEGORIA_VER: 'EJEMPLO_CATEGORIA_VER',
  EJEMPLO_CATEGORIA_CREAR: 'EJEMPLO_CATEGORIA_CREAR',
  EJEMPLO_CATEGORIA_EDITAR: 'EJEMPLO_CATEGORIA_EDITAR',
  EJEMPLO_CATEGORIA_ELIMINAR: 'EJEMPLO_CATEGORIA_ELIMINAR',

  // Ejemplo
  EJEMPLO_VER: 'EJEMPLO_VER',
  EJEMPLO_CREAR: 'EJEMPLO_CREAR',
  EJEMPLO_EDITAR: 'EJEMPLO_EDITAR',
  EJEMPLO_ELIMINAR: 'EJEMPLO_ELIMINAR',

  // Config - Ejemplo
  EJEMPLO_CONFIG: 'EJEMPLO_CONFIG',

  // Rutas del menú
  RUTA_DASHBOARD: 'RUTA_DASHBOARD',
  RUTA_USUARIOS: 'RUTA_USUARIOS',
  RUTA_ROLES: 'RUTA_ROLES',
  RUTA_ADMINISTRACION: 'RUTA_ADMINISTRACION',
  RUTA_SMTP_CLIENT: 'RUTA_SMTP_CLIENT',
  RUTA_PLANTILLA_NOTIFICACION: 'RUTA_PLANTILLA_NOTIFICACION',
  RUTA_ENVIO_NOTIFICACION: 'RUTA_ENVIO_NOTIFICACION',
  RUTA_EJEMPLOS: 'RUTA_EJEMPLOS',
  RUTA_EJEMPLO_CATEGORIAS: 'RUTA_EJEMPLO_CATEGORIAS',
  RUTA_EJEMPLO_CONFIG: 'RUTA_EJEMPLO_CONFIG',
} as const;
