
// Constantes de permisos del sistema
export const PERMISOS = {
  // Usuarios
  USUARIOS_VER: 'USUARIOS_VER',
  USUARIOS_CREAR: 'USUARIOS_CREAR',
  USUARIOS_EDITAR: 'USUARIOS_EDITAR',
  USUARIOS_ELIMINAR: 'USUARIOS_ELIMINAR',

  // Permisos
  PERMISOS_GESTIONAR: 'PERMISOS_GESTIONAR',

  // Roles
  ROLES_VER: 'ROLES_VER',
  ROLES_CREAR: 'ROLES_CREAR',
  ROLES_EDITAR: 'ROLES_EDITAR',
  ROLES_ELIMINAR: 'ROLES_ELIMINAR',

  // Archivos
  ARCHIVOS_VER: 'ARCHIVOS_VER',
  ARCHIVOS_CREAR: 'ARCHIVOS_CREAR',
  ARCHIVOS_EDITAR: 'ARCHIVOS_EDITAR',
  ARCHIVOS_ELIMINAR: 'ARCHIVOS_ELIMINAR',

  // Mensajes
  MENSAJES_VER: 'MENSAJES_VER',
  MENSAJES_CREAR: 'MENSAJES_CREAR',
  MENSAJES_EDITAR: 'MENSAJES_EDITAR',
  MENSAJES_ELIMINAR: 'MENSAJES_ELIMINAR',

  // Notificaciones
  NOTIFICACIONES_VER: 'NOTIFICACIONES_VER',
  NOTIFICACIONES_CREAR: 'NOTIFICACIONES_CREAR',
  NOTIFICACIONES_EDITAR: 'NOTIFICACIONES_EDITAR',
  NOTIFICACIONES_ELIMINAR: 'NOTIFICACIONES_ELIMINAR',

  // Auditoría
  AUDITORIA_VER: 'AUDITORIA_VER',
  AUDITORIA_CREAR: 'AUDITORIA_CREAR',
  AUDITORIA_EDITAR: 'AUDITORIA_EDITAR',
  AUDITORIA_ELIMINAR: 'AUDITORIA_ELIMINAR',
  AUDITORIA_PRESUPUESTO_HISTORIAL: 'AUDITORIA_PRESUPUESTO_HISTORIAL',

  // SMTP Client
  SMTP_CLIENT_VER: 'SMTP_CLIENT_VER',
  SMTP_CLIENT_CREAR: 'SMTP_CLIENT_CREAR',
  SMTP_CLIENT_EDITAR: 'SMTP_CLIENT_EDITAR',
  SMTP_CLIENT_ELIMINAR: 'SMTP_CLIENT_ELIMINAR',

  // Plantillas de Notificación
  PLANTILLA_NOTIFICACION_VER: 'PLANTILLA_NOTIFICACION_VER',
  PLANTILLA_NOTIFICACION_CREAR: 'PLANTILLA_NOTIFICACION_CREAR',
  PLANTILLA_NOTIFICACION_EDITAR: 'PLANTILLA_NOTIFICACION_EDITAR',
  PLANTILLA_NOTIFICACION_ELIMINAR: 'PLANTILLA_NOTIFICACION_ELIMINAR',

  // Envíos de Notificación
  ENVIO_NOTIFICACION_VER: 'ENVIO_NOTIFICACION_VER',
  ENVIO_NOTIFICACION_CREAR: 'ENVIO_NOTIFICACION_CREAR',
  ENVIO_NOTIFICACION_EDITAR: 'ENVIO_NOTIFICACION_EDITAR',
  ENVIO_NOTIFICACION_ELIMINAR: 'ENVIO_NOTIFICACION_ELIMINAR',

  // Ejemplo Categoría
  EJEMPLO_CATEGORIA_VER: 'EJEMPLO_CATEGORIA_VER',
  EJEMPLO_CATEGORIA_CREAR: 'EJEMPLO_CATEGORIA_CREAR',
  EJEMPLO_CATEGORIA_EDITAR: 'EJEMPLO_CATEGORIA_EDITAR',
  EJEMPLO_CATEGORIA_ELIMINAR: 'EJEMPLO_CATEGORIA_ELIMINAR',

  // Ejemplo
  EJEMPLO_VER: 'EJEMPLO_VER',
  EJEMPLO_CREAR: 'EJEMPLO_CREAR',
  EJEMPLO_EDITAR: 'EJEMPLO_EDITAR',
  EJEMPLO_ELIMINAR: 'EJEMPLO_ELIMINAR',

  // Config - Ejemplo
  EJEMPLO_CONFIG: 'EJEMPLO_CONFIG',

  // Clasificación Stock
  FAMILIA_VER: 'FAMILIA_VER',
  FAMILIA_CREAR: 'FAMILIA_CREAR',
  FAMILIA_EDITAR: 'FAMILIA_EDITAR',
  FAMILIA_ELIMINAR: 'FAMILIA_ELIMINAR',

  GRUPO_VER: 'GRUPO_VER',
  GRUPO_CREAR: 'GRUPO_CREAR',
  GRUPO_EDITAR: 'GRUPO_EDITAR',
  GRUPO_ELIMINAR: 'GRUPO_ELIMINAR',

  SUBGRUPO_VER: 'SUBGRUPO_VER',
  SUBGRUPO_CREAR: 'SUBGRUPO_CREAR',
  SUBGRUPO_EDITAR: 'SUBGRUPO_EDITAR',
  SUBGRUPO_ELIMINAR: 'SUBGRUPO_ELIMINAR',

  // Colores
  COLOR_VER: 'COLOR_VER',
  COLOR_CREAR: 'COLOR_CREAR',
  COLOR_EDITAR: 'COLOR_EDITAR',
  COLOR_ELIMINAR: 'COLOR_ELIMINAR',

  CURVA_COLOR_VER: 'CURVA_COLOR_VER',
  CURVA_COLOR_CREAR: 'CURVA_COLOR_CREAR',
  CURVA_COLOR_EDITAR: 'CURVA_COLOR_EDITAR',
  CURVA_COLOR_ELIMINAR: 'CURVA_COLOR_ELIMINAR',

  // Talles
  TALLE_VER: 'TALLE_VER',
  TALLE_CREAR: 'TALLE_CREAR',
  TALLE_EDITAR: 'TALLE_EDITAR',
  TALLE_ELIMINAR: 'TALLE_ELIMINAR',

  CURVA_TALLE_VER: 'CURVA_TALLE_VER',
  CURVA_TALLE_CREAR: 'CURVA_TALLE_CREAR',
  CURVA_TALLE_EDITAR: 'CURVA_TALLE_EDITAR',
  CURVA_TALLE_ELIMINAR: 'CURVA_TALLE_ELIMINAR',

  // Artículos
  ARTICULO_VER: 'ARTICULO_VER',
  ARTICULO_CREAR: 'ARTICULO_CREAR',
  ARTICULO_EDITAR: 'ARTICULO_EDITAR',
  ARTICULO_ELIMINAR: 'ARTICULO_ELIMINAR',
  ARTICULO_VER_COSTO: 'ARTICULO_VER_COSTO',
  ARTICULO_EDITAR_COSTO: 'ARTICULO_EDITAR_COSTO',

  // Listas de precios
  LISTA_PRECIO_VER: 'LISTA_PRECIO_VER',
  LISTA_PRECIO_CREAR: 'LISTA_PRECIO_CREAR',
  LISTA_PRECIO_EDITAR: 'LISTA_PRECIO_EDITAR',
  LISTA_PRECIO_ELIMINAR: 'LISTA_PRECIO_ELIMINAR',

  // Rutas del menú
  RUTA_LISTAS_PRECIOS: 'RUTA_LISTAS_PRECIOS',
  RUTA_DASHBOARD: 'RUTA_DASHBOARD',
  RUTA_USUARIOS: 'RUTA_USUARIOS',
  RUTA_ROLES: 'RUTA_ROLES',
  RUTA_ADMINISTRACION: 'RUTA_ADMINISTRACION',
  RUTA_SMTP_CLIENT: 'RUTA_SMTP_CLIENT',
  RUTA_PLANTILLA_NOTIFICACION: 'RUTA_PLANTILLA_NOTIFICACION',
  RUTA_ENVIO_NOTIFICACION: 'RUTA_ENVIO_NOTIFICACION',
  RUTA_EJEMPLOS: 'RUTA_EJEMPLOS',
  RUTA_EJEMPLO_CATEGORIAS: 'RUTA_EJEMPLO_CATEGORIAS',
  RUTA_EJEMPLO_CONFIG: 'RUTA_EJEMPLO_CONFIG',

  // Rutas del menú - Stock
  RUTA_STOCK: 'RUTA_STOCK',
  RUTA_FAMILIAS: 'RUTA_FAMILIAS',
  RUTA_GRUPOS: 'RUTA_GRUPOS',
  RUTA_SUBGRUPOS: 'RUTA_SUBGRUPOS',
  RUTA_COLORES: 'RUTA_COLORES',
  RUTA_CURVAS_COLOR: 'RUTA_CURVAS_COLOR',
  RUTA_TALLES: 'RUTA_TALLES',
  RUTA_CURVAS_TALLE: 'RUTA_CURVAS_TALLE',
  RUTA_ARTICULOS: 'RUTA_ARTICULOS',

  // Inventario - Ubicaciones
  UBICACION_VER: 'UBICACION_VER',
  UBICACION_CREAR: 'UBICACION_CREAR',
  UBICACION_EDITAR: 'UBICACION_EDITAR',
  UBICACION_ELIMINAR: 'UBICACION_ELIMINAR',

  // Inventario - Proveedores
  PROVEEDOR_VER: 'PROVEEDOR_VER',
  PROVEEDOR_CREAR: 'PROVEEDOR_CREAR',
  PROVEEDOR_EDITAR: 'PROVEEDOR_EDITAR',
  PROVEEDOR_ELIMINAR: 'PROVEEDOR_ELIMINAR',

  // Inventario - Clientes
  CLIENTE_VER: 'CLIENTE_VER',
  CLIENTE_CREAR: 'CLIENTE_CREAR',
  CLIENTE_EDITAR: 'CLIENTE_EDITAR',
  CLIENTE_ELIMINAR: 'CLIENTE_ELIMINAR',

  // Inventario - Movimientos
  MOVIMIENTO_INVENTARIO_VER: 'MOVIMIENTO_INVENTARIO_VER',
  MOVIMIENTO_INVENTARIO_CREAR: 'MOVIMIENTO_INVENTARIO_CREAR',

  // Inventario - Stock por ubicación
  STOCK_UBICACION_VER: 'STOCK_UBICACION_VER',

  // Rutas del menú - Inventario
  RUTA_INVENTARIO: 'RUTA_INVENTARIO',
  RUTA_UBICACIONES: 'RUTA_UBICACIONES',
  RUTA_PROVEEDORES: 'RUTA_PROVEEDORES',
  RUTA_CLIENTES: 'RUTA_CLIENTES',
  RUTA_MOVIMIENTOS: 'RUTA_MOVIMIENTOS',
  DASHBOARD_ANCLAS_VER: 'DASHBOARD_ANCLAS_VER',

  // Visitas (operativa)
  VISITA_VER: 'VISITA_VER',
  VISITA_CREAR: 'VISITA_CREAR',
  VISITA_EDITAR: 'VISITA_EDITAR',

  // Dashboard conversión
  DASHBOARD_CONVERSION_VER: 'DASHBOARD_CONVERSION_VER',

  // Configuración de visitas
  CARACTERISTICA_VISITANTE_VER: 'CARACTERISTICA_VISITANTE_VER',
  CARACTERISTICA_VISITANTE_CREAR: 'CARACTERISTICA_VISITANTE_CREAR',
  CARACTERISTICA_VISITANTE_EDITAR: 'CARACTERISTICA_VISITANTE_EDITAR',
  CARACTERISTICA_VISITANTE_ELIMINAR: 'CARACTERISTICA_VISITANTE_ELIMINAR',

  RAZON_NO_COMPRA_VER: 'RAZON_NO_COMPRA_VER',
  RAZON_NO_COMPRA_CREAR: 'RAZON_NO_COMPRA_CREAR',
  RAZON_NO_COMPRA_EDITAR: 'RAZON_NO_COMPRA_EDITAR',
  RAZON_NO_COMPRA_ELIMINAR: 'RAZON_NO_COMPRA_ELIMINAR',

  // Rutas del menú - Visitas
  RUTA_REGISTRO_VISITAS: 'RUTA_REGISTRO_VISITAS',
  RUTA_DASHBOARD_CONVERSION: 'RUTA_DASHBOARD_CONVERSION',
  RUTA_CONFIG_CARACTERISTICAS: 'RUTA_CONFIG_CARACTERISTICAS',
  RUTA_CONFIG_RAZONES_NO_COMPRA: 'RUTA_CONFIG_RAZONES_NO_COMPRA',
} as const;
